### ISSUE TITLE
Bay of Plenty ordering

### ISSUE THREAD

**Issue by silvispace** [linz/basemaps-config#696]
Hi basemaps team,

I noticed that the Bay of Plenty 0.1m Urban Aerial Photos (2018-2019) are behind the newer but lower resolution Bay of Plenty 0.2m Rural Aerial Photos (2021-2022) imagery. Just checking if this ordering is correct?

Thanks,
Grant

**Comment by dwsilk** [comment]
Yes this was intentional, the Bay of Plenty councils pointed out subdivisions that didn't exist in the 2018-2019 imagery that do exist in the 2021-2022 imagery and suggested that 20cm is good enough to display as priority over the older higher resolution imagery.

I think we will need the ability to filter/configure on "highest resolution" vs "most recent" as it is difficult to meet all needs with our combination of the two.

**Comment by dwsilk** [comment]
Change was made via https://github.com/linz/basemaps-config/pull/682

**Comment by silvispace** [comment]
Thanks Daniel, that makes sense.
